# Generated by Django 6.1 on 2026-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreading",
            name="source_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
